env:
  repo: "https://github.com/farrukh90/nodejs"
  app_version: "2.0.0"
  app_name: "nodejs"
  artifact_link: "us-central1-docker.pkg.dev/terraform-project-gregvalico/"

name: CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Google SA Authorization
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Docker Authorization
        run: |
          gcloud auth configure-docker \
          us-central1-docker.pkg.dev

      - name: Clone Repo
        run: |
          git clone ${{ env.repo }}
          
      - name: Switch Branch
        working-directory: ${{ env.app_name }}
        run: |
          git checkout ${{ env.app_version }}
          
      - name: Image Build
        working-directory: ${{ env.app_name }}
        run: |
          docker image build -t ${{ env.artifact_link }}${{ env.app_name }}/${{ env.app_name }}:${{ env.app_version }} .

      - name: Push Image
        working-directory: ${{ env.app_name }}
        run: |
          docker push ${{ env.artifact_link }}${{ env.app_name }}/${{ env.app_name }}:${{ env.app_version }}