env:
  repo: "https://github.com/farrukh90/nodejs"
  app_version: "1.0.0"
  app_name: "nodejs"
  artifact_link: "us-central1-docker.pkg.dev/terraform-project-gregvalico/"

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Google SA Authorization
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Docker Authorization
        run: |
          gcloud auth configure-docker \
          us-central1-docker.pkg.dev

      # Runs a set of commands using the runners shell
      - name: Clone Repo
        run: |
          git clone ${{ env.repo }}
          
      - name: Switch Branch
        working-directory: ${{ env.app_name }}
        run: |
          git checkout ${{ env.app_version }}
          
      - name: Image Build
        working-directory: ${{ env.app_name }}
        run: |
          docker image build -t ${{ env.artifact_link }}${{ env.app_name }}/${{ env.app_name }}:${{ env.app_version }} .

      - name: Push Image
        working-directory: ${{ env.app_name }}
        run: |
          docker push ${{ env.artifact_link }}${{ env.app_name }}/${{ env.app_name }}:${{ env.app_version }}